/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Github: typeof import('./src/components/Github.vue')['default']
    Mail: typeof import('./src/components/Mail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TranslateIcon: typeof import('./src/components/TranslateIcon.vue')['default']
  }
}
